---
title: "Code"
author: "Ainsley, Devon, Farah, Kayla"
date: "2024-07-23"
output: html_document
---

```{r}
<<<<<<< HEAD
library(tidyverse)

data<-read.csv('DoctorContacts.csv')

=======
library(readr)
library(tidyverse)
```
```{r}
data=read.csv("DoctorContacts.csv")
data
```
# Data Cleaning:
Data preparation and cleaning: some data cleaning. Depending on how clean your dataset is,
this might include: renaming columns, removing columns or rows, mutating columns,
subsetting (or filtering) the data based on interesting questions to investigate

# Rename the columns:
```{r}
DoctorContacts <- data %>%
  rename(visits = mdu, log_coinsurance = lc, log_api = lpi,
         log_max_deductible = fmde, num_disease = ndisease,
         log_income = linc, log_fam_size = lfam, schooling= educdec)
View(DoctorContacts)

```
# Q

```{r}
updatedr<-read.csv('UpdatedDoctorContacts.csv')
```

```{r}
updatedr$sqrt_insurance = sqrt(updatedr$insurance)
updatedr$sqrt_payment = sqrt(updatedr$payment)
updatedr$sqrt_deductible = sqrt(updatedr$deductible)
updatedr$sqrt_income = sqrt(updatedr$income)
updatedr$sqrt_family = sqrt(updatedr$family)
View(updatedr)
```

```{r}
write.csv(updatedr, file="DrContactsNew.csv")
```

