---
title: "Farah_plots_initial"
output: html_document
date: "2024-07-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
# Read in data
DoctorContacts <- read.csv("DoctorContacts.csv")
```

```{r}
# Load packages
library(tidyverse)
library(ggplot2)
```

```{r}
# Rename columns
DoctorContacts <- DoctorContacts %>%
  rename(visits = mdu, log_coinsurance = lc, log_api = lpi,
         log_max_deductible = fmde, num_disease = ndisease,
         log_income = linc, log_fam_size = lfam, schooling= educdec)
head(DoctorContacts)
```
Get column names:

```{r}
names(DoctorContacts)
```

(Visualization): 
Does an individual’s number of chronic diseases (num_disease) affect their self-rate health score (health)? 
Null: An individual’s number of chronic diseases (num_disease) has no effect on their self-rate health score (health).
Alt: An individual’s number of chronic diseases (num_disease) has an effect on their self-rate health score (health).

```{r}
table(DoctorContacts$health, DoctorContacts$num_disease)
```


```{r}
ggplot(DoctorContacts, aes(x=health, y=num_disease, fill=health)) + geom_boxplot() 
```

```{r}
anova<-aov(num_disease~health, data=DoctorContacts)
summary(anova)
```
```{r}
TukeyHSD(anova, conf.level = 0.95)
```
```{r}
plot(TukeyHSD(anova, conf.level = 0.95))
```

