---
title: "LM_Ainsley"
author: "Ainsley McLaughlin"
date: "2024-07-25"
output: html_document
---

```{r}
#read in data/get packages
library(readr)
library(tidyverse)
library(dplyr)

DoctorContacts <- read.csv("DoctorContacts.csv")
View(DoctorContacts)

```

#
```{r}
# Rename columns
DoctorContacts <- DoctorContacts %>%
  rename(visits = mdu, log_coinsurance = lc, log_api = lpi,
         log_max_deductible = fmde, num_disease = ndisease,
         log_income = linc, log_fam_size = lfam, schooling= educdec)
View(DoctorContacts)
```
#
```{r}
# Delete extra index column
DoctorContacts <- select(DoctorContacts, -rownames)
```
#
```{r}
# Undo log transformations
DoctorContacts$insurance = exp(DoctorContacts$log_coinsurance)
DoctorContacts$payment = exp(DoctorContacts$log_api)
DoctorContacts$deductible = exp(DoctorContacts$log_max_deductible)
DoctorContacts$income = exp(DoctorContacts$log_income)
DoctorContacts$family = exp(DoctorContacts$log_fam_size)
```

#
```{r}
#write to a new csv with the updates:

```

#
```{r}
```
#
```{r}
```
#
```{r}
```

#
```{r}
```

#
```{r}
```

#
```{r}
```

#
```{r}
```
#
```{r}
```

#
```{r}
```

#
```{r}
```